# Generated by Django 5.2.4 on 2025-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_task_created_at_alter_task_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено:'),
        ),
    ]
